name: tbo_the_best_one
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.4.1
  barcode_widget: ^1.5.0
  flutter_local_notifications: ^4.0.0
  carousel_slider: ^2.3.1
  flutter_rating_bar: ^3.2.0+1
  flutter_widget_from_html_core: ^0.5.1+4
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.3
  shimmer: ^1.1.2
  image_picker: ^0.6.7+22
  faker: ^1.2.1
  provider: ^4.3.2+2
  in_app_review: ^1.0.4
  geolocator: ^6.1.3
  geocoding: ^1.0.5
  lottie: ^0.7.0+1
  google_maps_place_picker: ^1.0.0
  intl_phone_field: ^1.4.2
  intl: ^0.16.1
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  dio: ^3.0.10
  modal_progress_hud: ^0.1.3
  fluttertoast: ^7.1.2
  device_info: ^1.0.0
  shared_preferences: ^0.5.12+4
  flutter_spinkit: ^4.1.2+1
  url_launcher: ^5.7.8
  showcaseview: ^0.1.6
  share: ^0.6.5+4
  razorpay_flutter: ^1.2.2
  permission_handler: ^5.0.1+1
  html_unescape: ^1.0.2
  flutter_sound: ^7.8.0
  speech_to_text: ^3.1.0
  path_provider: ^1.6.27
  image_pickers: ^1.0.8+7
  speech_recognition:
    git:
      url: https://github.com/webeverde/speech_recognition.git
      ref: master
  firebase_messaging: ^7.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  pretty_dio_logger: ^1.1.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 900
